site_name: NodeMCU Documentation
site_description: Description of the NodeMCU documentation
repo_url: https://github.com/nodemcu/nodemcu-firmware/

theme:
  name: "readthedocs"
strict: true

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

#requird due to https://github.com/rtfd/readthedocs.org/issues/1313
#see http://mkdocs.readthedocs.org/en/latest/user-guide/styling-your-docs/#customising-a-theme
extra_css:
- css/extra.css
extra_javascript:
- js/extra.js

pages:
- Overview: 'index.md'
- Basics:
    - Getting started: 'en/getting-started.md'
    - Building the firmware: 'en/build.md'
    - Flashing the firmware: 'en/flash.md'
    - Uploading code: 'en/upload.md'
    - Support: 'en/support.md'
- FAQs:
    - Lua Developer FAQ: 'en/lua-developer-faq.md'
    - Extension Developer FAQ: 'en/extn-developer-faq.md'
    - Hardware FAQ: 'en/hardware-faq.md'
- Whitepapers:
    - Filesystem on SD card: 'en/sdcard.md'
    - Internal filesystem: 'en/spiffs.md'
    - Lua Compact Debug (LCD): 'en/lcd.md'
    - Lua Flash Store (LFS): 'en/lfs.md'
- Modules:
    - 'adc': 'en/modules/adc.md'
    - 'ads1115' : 'en/modules/ads1115.md'
    - 'adxl345': 'en/modules/adxl345.md'
    - 'am2320': 'en/modules/am2320.md'
    - 'apa102': 'en/modules/apa102.md'
    - 'bit': 'en/modules/bit.md'
    - 'bloom' : 'en/modules/bloom.md'
    - 'bme280': 'en/modules/bme280.md'
    - 'bme680': 'en/modules/bme680.md'
    - 'bmp085': 'en/modules/bmp085.md'
    - 'cjson': 'en/modules/cjson.md'
    - 'coap': 'en/modules/coap.md'
    - 'color-utils': 'en/modules/color-utils.md'
    - 'cron': 'en/modules/cron.md'
    - 'crypto': 'en/modules/crypto.md'
    - 'dht': 'en/modules/dht.md'
    - 'ds18b20': 'en/modules/ds18b20.md'
    - 'encoder': 'en/modules/encoder.md'
    - 'enduser setup': 'en/modules/enduser-setup.md'
    - 'file': 'en/modules/file.md'
    - 'gdbstub': 'en/modules/gdbstub.md'
    - 'gpio': 'en/modules/gpio.md'
    - 'hdc1080': 'en/modules/hdc1080.md'
    - 'hmc5883l': 'en/modules/hmc5883l.md'
    - 'http': 'en/modules/http.md'
    - 'hx711' : 'en/modules/hx711.md'
    - 'i2c' : 'en/modules/i2c.md'
    - 'l3g4200d' : 'en/modules/l3g4200d.md'
    - 'mcp4725': 'en/modules/mcp4725.md'
    - 'mdns': 'en/modules/mdns.md'
    - 'mqtt': 'en/modules/mqtt.md'
    - 'net': 'en/modules/net.md'
    - 'node': 'en/modules/node.md'
    - 'ow (1-Wire)': 'en/modules/ow.md'
    - 'pcm' : 'en/modules/pcm.md'
    - 'perf': 'en/modules/perf.md'
    - 'pwm' : 'en/modules/pwm.md'
    - 'rc' : 'en/modules/rc.md'
    - 'rfswitch' : 'en/modules/rfswitch.md'
    - 'rotary' : 'en/modules/rotary.md'
    - 'rtcfifo': 'en/modules/rtcfifo.md'
    - 'rtcmem': 'en/modules/rtcmem.md'
    - 'rtctime': 'en/modules/rtctime.md'
    - 'si7021' : 'en/modules/si7021.md'
    - 'sigma delta': 'en/modules/sigma-delta.md'
    - 'sjson': 'en/modules/sjson.md'
    - 'sntp': 'en/modules/sntp.md'
    - 'somfy': 'en/modules/somfy.md'
    - 'spi': 'en/modules/spi.md'
    - 'sqlite3': 'en/modules/sqlite3.md'
    - 'struct': 'en/modules/struct.md'
    - 'switec': 'en/modules/switec.md'
    - 'tcs34725': 'en/modules/tcs34725.md'
    - 'tls': 'en/modules/tls.md'
    - 'tm1829': 'en/modules/tm1829.md'
    - 'tmr': 'en/modules/tmr.md'
    - 'tsl2561': 'en/modules/tsl2561.md'
    - 'u8g2': 'en/modules/u8g2.md'
    - 'uart': 'en/modules/uart.md'
    - 'ucg': 'en/modules/ucg.md'
    - 'websocket': 'en/modules/websocket.md'
    - 'wifi': 'en/modules/wifi.md'
    - 'wifi.monitor': 'en/modules/wifi_monitor.md'
    - 'wps': 'en/modules/wps.md'
    - 'ws2801': 'en/modules/ws2801.md'
    - 'ws2812': 'en/modules/ws2812.md'
    - 'ws2812-effects': 'en/modules/ws2812-effects.md'
    - 'xpt2046': 'en/modules/xpt2046.md'
